[flavor]
dark = "catppuccin-mocha"

[mgr]
cwd = { fg = "#89b4fa" }

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[indicator]
padding = { open = "█", close = "█" }

[status]
overall = { bg = "#181825" }
sep_left = { open = "█", close = "█" }
sep_right = { open = "█", close = "█" }
